/* © 2025 Casey Koons All rights reserved */

/* Model update utility - query APIs and update model defaults */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "../include/argo_http.h"
#include "../include/argo_error.h"

static void print_usage(const char* prog) {
    printf("Usage: %s [options]\n", prog);
    printf("\n");
    printf("Query API providers and generate argo_local_models.h\n");
    printf("\n");
    printf("Options:\n");
    printf("  --output FILE, -o FILE   Output file (default: include/argo_local_models.h)\n");
    printf("  --help, -h               Show this help\n");
    printf("\n");
}

/*
 * Model query functions return current defaults
 * Future: Could query provider APIs to get latest model IDs
 * Would require: API key access, JSON parsing (use argo_json.h)
 */

static char* query_claude_model(void) {
    printf("Checking Claude models... ");
    fflush(stdout);

    /* Could query API for latest models if needed */
    printf("(using default - API query not implemented)\n");
    return strdup("claude-sonnet-4-5-20250929");
}

static char* query_openai_model(void) {
    printf("Checking OpenAI models... ");
    fflush(stdout);

    printf("(using default - API query not implemented)\n");
    return strdup("gpt-4o");
}

static char* query_gemini_model(void) {
    printf("Checking Gemini models... ");
    fflush(stdout);

    printf("(using default - API query not implemented)\n");
    return strdup("gemini-2.5-flash");
}

static char* query_grok_model(void) {
    printf("Checking Grok models... ");
    fflush(stdout);

    printf("(using default - no public API)\n");
    return strdup("grok-3");
}

static char* query_deepseek_model(void) {
    printf("Checking DeepSeek models... ");
    fflush(stdout);

    printf("(using default - no public API)\n");
    return strdup("deepseek-chat");
}

static char* query_openrouter_model(void) {
    printf("Checking OpenRouter models... ");
    fflush(stdout);

    printf("(using default - API query not implemented)\n");
    return strdup("anthropic/claude-sonnet-4.5");
}

static int generate_header(const char* output_file,
                          const char* claude_model,
                          const char* openai_model,
                          const char* gemini_model,
                          const char* grok_model,
                          const char* deepseek_model,
                          const char* openrouter_model) {
    FILE* fp = fopen(output_file, "w");
    if (!fp) {
        fprintf(stderr, "Error: Failed to create %s\n", output_file);
        return -1;
    }

    /* Get current date */
    time_t now = time(NULL);
    struct tm* tm_info = localtime(&now);
    char date_str[32];
    strftime(date_str, sizeof(date_str), "%Y-%m-%d", tm_info);

    /* Write header */
    fprintf(fp, "/* © 2025 Casey Koons All rights reserved */\n");
    fprintf(fp, "/* Auto-generated by scripts/argo_update_models on %s */\n", date_str);
    fprintf(fp, "/* DO NOT EDIT MANUALLY - regenerate with: make update-models */\n");
    fprintf(fp, "\n");
    fprintf(fp, "#ifndef ARGO_LOCAL_MODELS_H\n");
    fprintf(fp, "#define ARGO_LOCAL_MODELS_H\n");
    fprintf(fp, "\n");
    fprintf(fp, "/*\n");
    fprintf(fp, " * Current model preferences from API providers\n");
    fprintf(fp, " * This file is git-ignored and overrides defaults in argo_api_providers.h\n");
    fprintf(fp, " */\n");
    fprintf(fp, "\n");
    fprintf(fp, "/* Anthropic Claude Models - Verified: %s */\n", date_str);
    fprintf(fp, "#define CLAUDE_DEFAULT_MODEL \"%s\"\n", claude_model);
    fprintf(fp, "\n");
    fprintf(fp, "/* OpenAI Models - Verified: %s */\n", date_str);
    fprintf(fp, "#define OPENAI_DEFAULT_MODEL \"%s\"\n", openai_model);
    fprintf(fp, "\n");
    fprintf(fp, "/* Google Gemini Models - Verified: %s */\n", date_str);
    fprintf(fp, "#define GEMINI_DEFAULT_MODEL \"%s\"\n", gemini_model);
    fprintf(fp, "\n");
    fprintf(fp, "/* xAI Grok Models - Verified: %s */\n", date_str);
    fprintf(fp, "#define GROK_DEFAULT_MODEL \"%s\"\n", grok_model);
    fprintf(fp, "\n");
    fprintf(fp, "/* DeepSeek Models - Verified: %s */\n", date_str);
    fprintf(fp, "#define DEEPSEEK_DEFAULT_MODEL \"%s\"\n", deepseek_model);
    fprintf(fp, "\n");
    fprintf(fp, "/* OpenRouter Models - Verified: %s */\n", date_str);
    fprintf(fp, "#define OPENROUTER_DEFAULT_MODEL \"%s\"\n", openrouter_model);
    fprintf(fp, "\n");
    fprintf(fp, "#endif /* ARGO_LOCAL_MODELS_H */\n");

    fclose(fp);
    return 0;
}

int main(int argc, char* argv[]) {
    const char* output_file = "include/argo_local_models.h";

    /* Parse arguments */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--output") == 0 || strcmp(argv[i], "-o") == 0) {
            if (i + 1 < argc) {
                output_file = argv[++i];
            } else {
                fprintf(stderr, "Error: --output requires argument\n");
                return 1;
            }
        } else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown option: %s\n", argv[i]);
            print_usage(argv[0]);
            return 1;
        }
    }

    printf("Argo Model Update Script\n");
    printf("========================\n");
    printf("\n");
    printf("Querying API providers for current models...\n");
    printf("\n");

    /* Query each provider */
    char* claude_model = query_claude_model();
    char* openai_model = query_openai_model();
    char* gemini_model = query_gemini_model();
    char* grok_model = query_grok_model();
    char* deepseek_model = query_deepseek_model();
    char* openrouter_model = query_openrouter_model();

    /* Check for failures */
    if (!claude_model || !openai_model || !gemini_model ||
        !grok_model || !deepseek_model || !openrouter_model) {
        fprintf(stderr, "Error: Failed to query some models\n");
        free(claude_model);
        free(openai_model);
        free(gemini_model);
        free(grok_model);
        free(deepseek_model);
        free(openrouter_model);
        return 1;
    }

    printf("\n");
    printf("Generating %s...\n", output_file);

    /* Generate header file */
    int result = generate_header(output_file,
                                 claude_model, openai_model, gemini_model,
                                 grok_model, deepseek_model, openrouter_model);

    if (result == 0) {
        printf("✓ Done!\n");
        printf("\n");
        printf("Model configuration updated:\n");
        printf("  Claude:     %s\n", claude_model);
        printf("  OpenAI:     %s\n", openai_model);
        printf("  Gemini:     %s\n", gemini_model);
        printf("  Grok:       %s\n", grok_model);
        printf("  DeepSeek:   %s\n", deepseek_model);
        printf("  OpenRouter: %s\n", openrouter_model);
        printf("\n");
        printf("To use these models, rebuild with: make clean && make\n");
        printf("\n");
    }

    /* Cleanup */
    free(claude_model);
    free(openai_model);
    free(gemini_model);
    free(grok_model);
    free(deepseek_model);
    free(openrouter_model);

    return result;
}